# Generated by Django 2.2.7 on 2020-11-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cardprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardprogress',
            name='last_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
