# Generated by Django 2.2.7 on 2020-10-04 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('objective', models.CharField(default='', max_length=50)),
                ('time_until_completion', models.IntegerField(default=0)),
                ('completed_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MyPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_users', models.IntegerField(default=0)),
                ('num_topics', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications', models.BooleanField(blank=True, default=True)),
                ('sounds', models.BooleanField(blank=True, default=True)),
                ('password', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('category', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Calendar')),
                ('goal_list', models.ManyToManyField(to='app.Goal')),
                ('topic_list', models.ManyToManyField(to='app.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_list', models.ManyToManyField(to='app.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=10)),
                ('difficulty', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('content', models.CharField(default='', max_length=50)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='list_of_topics',
            field=models.ManyToManyField(to='app.Topic'),
        ),
    ]
