# Generated by Django 2.2.7 on 2020-10-06 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='calendar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='goal_list',
        ),
        migrations.RemoveField(
            model_name='user',
            name='topic_list',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='list_of_topics',
            field=models.ManyToManyField(to='app.Deck'),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='card_list',
            field=models.ManyToManyField(to='app.Deck'),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Deck'),
        ),
        migrations.AddField(
            model_name='user',
            name='deck_list',
            field=models.ManyToManyField(to='app.Deck'),
        ),
    ]
