# Generated by Django 2.2.7 on 2020-10-30 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='complete',
        ),
    ]
