from __future__ import unicode_literals

from django.db import migrations, models
from app.models import Course, Card, Skill


def add_mock_guitar_course(apps, schema_editor): #declare a function to add this data
	d = Course(name='Guitar')
	d.save()

	transcribing = Skill(name="Transcribing", course=d)
	transcribing.save()
	knowledge = Skill(name="Knowledge", course=d)
	knowledge.save()
	repertoire = Skill(name="Repertoire", course=d)
	repertoire.save()
	improvisation = Skill(name="Improvisation", course=d)
	improvisation.save()
	technique = Skill(name="Technique", course=d)
	technique.save()

	c1 = Card(title='Perfect 4th', course=d, skill=transcribing, level=1, duration=5, view_count=0, content='Lorem ipsum')
	c1.save()
	c2 = Card(title='Perfect 5th', course=d, skill=transcribing, level=1, duration=5, view_count=0, content='Lorem ipsum')
	c2.save()
	c3 = Card(title='Minor 3rd', course=d, skill=transcribing, level=3, duration=5, view_count=0, content='Lorem ipsum')
	c3.save()
	c4 = Card(title='Major 3rd', course=d, skill=transcribing, level=2, duration=5, view_count=0, content='Lorem ipsum')
	c4.save()
	c5 = Card(title='Perfect Unison', course=d, skill=transcribing, level=1, duration=5, view_count=0, content='Lorem ipsum')
	c5.save()
	c6 = Card(title='Modes', course=d, skill=knowledge, level=2, duration=15, view_count=0, content='Lorem ipsum')
	c6.save()
	c7 = Card(title='Triad arpeggios', course=d, skill=knowledge, level=2, duration=15, view_count=0, content='Lorem ipsum')
	c7.save()
	c8 = Card(title='Triads', course=d, skill=knowledge, level=2, duration=15, view_count=0, content='Lorem ipsum')
	c8.save()
	c9 = Card(title='Seventh arpeggios', course=d, skill=knowledge, level=3, duration=15, view_count=0, content='Lorem ipsum')
	c9.save()
	c10 = Card(title='Reptilia', course=d, skill=repertoire, level=3, duration=15, view_count=0, content='Lorem ipsum')
	c10.save()
	c11 = Card(title='People Everywhere (Still Alive)', course=d, skill=repertoire, level=4, duration=15, view_count=0, content='Lorem ipsum')
	c11.save()
	c12 = Card(title='Im In Your Mind', course=d, skill=repertoire, level=1, duration=15, view_count=0, content='Lorem ipsum')
	c12.save()
	c13 = Card(title='Summertime', course=d, skill=repertoire, level=5, duration=15, view_count=0, content='Lorem ipsum')
	c13.save()
	c14 = Card(title='Golden Brown', course=d, skill=repertoire, level=3, duration=15, view_count=0, content='Lorem ipsum')
	c14.save()
	c15 = Card(title='Minimum Movement Exercise', course=d, skill=technique, level=2, duration=10, view_count=0, content='Lorem ipsum')
	c15.save()
	c16 = Card(title='Finger Gym', course=d, skill=technique, level=2, duration=10, view_count=0, content='Lorem ipsum')
	c16.save()
	c17 = Card(title='Quality Control Exercise', course=d, skill=technique, level=2, duration=10, view_count=0, content='Lorem ipsum')
	c17.save()
	c18 = Card(title='Spider Exercise', course=d, skill=technique, level=2, duration=10, view_count=0, content='Lorem ipsum')
	c18.save()
	c19 = Card(title='Scale Picking', course=d, skill=technique, level=2, duration=10, view_count=0, content='Lorem ipsum')
	c19.save()
	c20 = Card(title='A Minor Improvisation', course=d, skill=improvisation, level=2, duration=15, view_count=0, content='Lorem ipsum')
	c20.save()
	c21 = Card(title='G Minor Improvisation', course=d, skill=improvisation, level=2, duration=15, view_count=0, content='Lorem ipsum')
	c21.save()
	c22 = Card(title='Chord Tone Improvisation', course=d, skill=improvisation, level=4, duration=15, view_count=0, content='Lorem ipsum')
	c22.save()
	c23 = Card(title='Pentatonic Blues Improvisation', course=d, skill=improvisation, level=1, duration=15, view_count=0, content='Lorem ipsum')
	c23.save()
	c24 = Card(title='A Myxolidian Improvisation', course=d, skill=improvisation, level=3, duration=15, view_count=0, content='Lorem ipsum')
	c24.save()
	c25 = Card(title='Seventh chords', course=d, skill=knowledge, level=3, duration=15, view_count=0, content='Lorem ipsum')
	c25.save()
	c26 = Card(title='A major scale', course=d, skill=knowledge, level=2, duration=15, view_count=0, content='A B C# D E F# G# A')
	c26.save()
	c27 = Card(title='Bb major scale', course=d, skill=knowledge, level=2, duration=15, view_count=0, content='Bb C D Eb F G A Bb')
	c27.save()
	c28 = Card(title='B major scale', course=d, skill=knowledge, level=2, duration=15, view_count=0, content='B C# D# E F# G# A# B')
	c28.save()
	c29 = Card(title='C major scale', course=d, skill=knowledge, level=2, duration=15, view_count=0, content='C D E F G A B C')
	c29.save()
	c30 = Card(title='Db major scale', course=d, skill=knowledge, level=2, duration=15, view_count=0, content='Db Eb F Gb Ab Bb C Db')
	c30.save()
	c31 = Card(title='D major scale', course=d, skill=knowledge, level=2, duration=15, view_count=0, content='D E F# G A B C# D')
	c31.save()
	c32 = Card(title='Eb major scale', course=d, skill=knowledge, level=2, duration=15, view_count=0, content='Eb F G Ab Bb C D Eb')
	c32.save()
	c33 = Card(title='E major scale', course=d, skill=knowledge, level=2, duration=15, view_count=0, content='E F# G# A B C# D# E')
	c33.save()
	c34 = Card(title='F major scale', course=d, skill=knowledge, level=2, duration=15, view_count=0, content='F G A Bb C D E F')
	c34.save()
	c35 = Card(title='Per 4 and 5 Ear Trainer', course=d, skill=transcribing, level=1, duration=15, view_count=0, content='Practice Level 1 of Justin Guitar Ear Trainer')
	c35.save()
	c36 = Card(title='Maj 3 and 2 Ear Trainer', course=d, skill=transcribing, level=1, duration=15, view_count=0, content='Practice Level 2 of Justin Guitar Ear Trainer')
	c36.save()
	c37 = Card(title='Maj 6 and 7 Ear Trainer', course=d, skill=transcribing, level=1, duration=15, view_count=0, content='Practice Level 3 of Justin Guitar Ear Trainer')
	c37.save()
	c38 = Card(title='Cory Wong Warmup #1', course=d, skill=technique, level=4, duration=15, view_count=0, content='Arepggios around the world: Play three notes of a triad in three octives, then shift conterclockwise along the Circle of Fifths.')
	c38.save()
	c39 = Card(title='Cory Wong Warmup #2', course=d, skill=technique, level=4, duration=15, view_count=0, content='Chromatic Approach Arpeggios: Use two octaves plus an extra root up top as a turnaround point.')
	c39.save()
	c40 = Card(title='Cory Wong Warmup #3', course=d, skill=technique, level=4, duration=15, view_count=0, content='Displacing Accents: Practice accenting muted strums. Mute the strings with your fretting hand and play sixteenth notes. USE A METRONOME.')
	c40.save()
	c41 = Card(title='Gravity', course=d, skill=repertoire, level=4, duration=15, view_count=0, content='Gravity by John Mayer')
	c41.save()
	c42 = Card(title='Bold as Love', course=d, skill=repertoire, level=4, duration=15, view_count=0, content='Bold as Love by Jimi Hendrix')
	c42.save()

class Migration(migrations.Migration):

	dependencies = [
		('app', '0002_remove_card_complete'),  # the name of the migration before this migration
	]

	operations = [
		migrations.RunPython(add_mock_guitar_course) # the name of the function we declared
	]