# Generated by Django 2.2.7 on 2020-11-11 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Course'),
        ),
    ]
