# Generated by Django 2.2.7 on 2020-11-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201111_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='num_cards',
            field=models.IntegerField(default=0),
        ),
    ]
