# Generated by Django 2.2.7 on 2020-12-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_deck_num_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='content',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
