# Generated by Django 2.2.7 on 2020-12-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_databases_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='cards',
            field=models.CharField(default='', max_length=500),
        ),
    ]
