# Generated by Django 2.2.7 on 2020-12-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201203_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image_path',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='link',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
